# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wtcMainWindow2.ui'
#
# Created: Mon May 25 23:19:08 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblQuestion = QtGui.QLabel(self.centralwidget)
        self.lblQuestion.setGeometry(QtCore.QRect(10, 20, 771, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblQuestion.setFont(font)
        self.lblQuestion.setAutoFillBackground(True)
        self.lblQuestion.setFrameShadow(QtGui.QFrame.Plain)
        self.lblQuestion.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblQuestion.setObjectName("lblQuestion")
        self.btnNext = QtGui.QPushButton(self.centralwidget)
        self.btnNext.setGeometry(QtCore.QRect(630, 210, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnNext.setFont(font)
        self.btnNext.setObjectName("btnNext")
        self.btnPrev = QtGui.QPushButton(self.centralwidget)
        self.btnPrev.setGeometry(QtCore.QRect(630, 280, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnPrev.setFont(font)
        self.btnPrev.setObjectName("btnPrev")
        self.btnSubmit = QtGui.QPushButton(self.centralwidget)
        self.btnSubmit.setGeometry(QtCore.QRect(630, 400, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSubmit.setFont(font)
        self.btnSubmit.setObjectName("btnSubmit")
        self.btnReset = QtGui.QPushButton(self.centralwidget)
        self.btnReset.setGeometry(QtCore.QRect(630, 470, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnReset.setFont(font)
        self.btnReset.setObjectName("btnReset")
        self.lblCounter = QtGui.QLabel(self.centralwidget)
        self.lblCounter.setGeometry(QtCore.QRect(630, 120, 140, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblCounter.setFont(font)
        self.lblCounter.setAutoFillBackground(True)
        self.lblCounter.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCounter.setObjectName("lblCounter")
        self.gbAnswers = QtGui.QGroupBox(self.centralwidget)
        self.gbAnswers.setGeometry(QtCore.QRect(10, 120, 600, 400))
        self.gbAnswers.setTitle("")
        self.gbAnswers.setFlat(False)
        self.gbAnswers.setObjectName("gbAnswers")
        self.rbAnswerOne = QtGui.QRadioButton(self.gbAnswers)
        self.rbAnswerOne.setGeometry(QtCore.QRect(20, 10, 550, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbAnswerOne.setFont(font)
        self.rbAnswerOne.setObjectName("rbAnswerOne")
        self.rbAnswerTwo = QtGui.QRadioButton(self.gbAnswers)
        self.rbAnswerTwo.setGeometry(QtCore.QRect(20, 90, 550, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbAnswerTwo.setFont(font)
        self.rbAnswerTwo.setObjectName("rbAnswerTwo")
        self.rbAnswerThree = QtGui.QRadioButton(self.gbAnswers)
        self.rbAnswerThree.setGeometry(QtCore.QRect(20, 170, 550, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbAnswerThree.setFont(font)
        self.rbAnswerThree.setObjectName("rbAnswerThree")
        self.rbAnswerFour = QtGui.QRadioButton(self.gbAnswers)
        self.rbAnswerFour.setGeometry(QtCore.QRect(20, 250, 550, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbAnswerFour.setFont(font)
        self.rbAnswerFour.setObjectName("rbAnswerFour")
        self.rbAnswerFive = QtGui.QRadioButton(self.gbAnswers)
        self.rbAnswerFive.setGeometry(QtCore.QRect(20, 330, 550, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbAnswerFive.setFont(font)
        self.rbAnswerFive.setObjectName("rbAnswerFive")
        self.rbNone = QtGui.QRadioButton(self.gbAnswers)
        self.rbNone.setEnabled(True)
        self.rbNone.setGeometry(QtCore.QRect(540, 380, 20, 10))
        self.rbNone.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rbNone.setText("")
        self.rbNone.setObjectName("rbNone")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(mainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionExit = QtGui.QAction(mainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(mainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuMenu.addAction(self.actionNew)
        self.menuMenu.addAction(self.actionAbout)
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.btnNext, self.btnPrev)
        mainWindow.setTabOrder(self.btnPrev, self.btnSubmit)
        mainWindow.setTabOrder(self.btnSubmit, self.btnReset)
        mainWindow.setTabOrder(self.btnReset, self.rbAnswerOne)
        mainWindow.setTabOrder(self.rbAnswerOne, self.rbAnswerTwo)
        mainWindow.setTabOrder(self.rbAnswerTwo, self.rbNone)
        mainWindow.setTabOrder(self.rbNone, self.rbAnswerThree)
        mainWindow.setTabOrder(self.rbAnswerThree, self.rbAnswerFour)
        mainWindow.setTabOrder(self.rbAnswerFour, self.rbAnswerFive)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "What\'s the Capital?", None, QtGui.QApplication.UnicodeUTF8))
        self.lblQuestion.setText(QtGui.QApplication.translate("mainWindow", "What\'s the Capital?", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNext.setText(QtGui.QApplication.translate("mainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPrev.setText(QtGui.QApplication.translate("mainWindow", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSubmit.setText(QtGui.QApplication.translate("mainWindow", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReset.setText(QtGui.QApplication.translate("mainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCounter.setText(QtGui.QApplication.translate("mainWindow", "0 of 10", None, QtGui.QApplication.UnicodeUTF8))
        self.rbAnswerOne.setText(QtGui.QApplication.translate("mainWindow", "Answer Option #1", None, QtGui.QApplication.UnicodeUTF8))
        self.rbAnswerTwo.setText(QtGui.QApplication.translate("mainWindow", "Answer Option #2", None, QtGui.QApplication.UnicodeUTF8))
        self.rbAnswerThree.setText(QtGui.QApplication.translate("mainWindow", "Answer Option #3", None, QtGui.QApplication.UnicodeUTF8))
        self.rbAnswerFour.setText(QtGui.QApplication.translate("mainWindow", "Answer Option #4", None, QtGui.QApplication.UnicodeUTF8))
        self.rbAnswerFive.setText(QtGui.QApplication.translate("mainWindow", "Answer Option #5", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("mainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("mainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("mainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("mainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

